### PR TITLE
ome.ts: update with ome-zarr 0.5

### PR DESCRIPTION
**Pull request by joshmoore**
[RFC-2](https://ngff.openmicroscopy.org/rfc/2) has now been adopted. In preparation for the OME-Zarr 0.5 release, this PR wraps the NGFF metadata in the Zarr metadata within an "ome" block. This checks for that block and if it exists unwraps the necessary metadata if the Zarr version is 3.

Originally opened as #616 

cc: @normanrz

### CODE REVIEW

**Comment by joshmoore** [comment]
Pushed a format fix.

**Comment by jbms** [comment]
Thanks!

**Comment by jbms** [comment]
Can you fix formatting with `npm run format:fix` ?

**Comment by joshmoore** [comment]
TIL:

```
npm i prettier
npm run format:fix
```

Commit pushed

<details><summary>(and additional changes ignored)</summary>

```
diff --git a/src/ui/viewer_settings.ts b/src/ui/viewer_settings.ts
index 8744cb6f..a0c936f9 100644
--- a/src/ui/viewer_settings.ts
+++ b/src/ui/viewer_settings.ts
@@ -125,7 +125,10 @@ export class ViewerSettingsPanel extends SidePanel {
     );
     addCheckbox("Wire frame rendering", viewer.wireFrame);
     addCheckbox("Enable prefetching", viewer.chunkQueueManager.enablePrefetch);
-    addCheckbox("Enable adaptive downsampling", viewer.enableAdaptiveDownsampling);
+    addCheckbox(
+      "Enable adaptive downsampling",
+      viewer.enableAdaptiveDownsampling,
+    );
 
     const addColor = (label: string, value: WatchableValueInterface<vec3>) => {
       const labelElement = document.createElement("label");
diff --git a/src/util/framerate.spec.ts b/src/util/framerate.spec.ts
index e3b54839..6f96a4bb 100644
--- a/src/util/framerate.spec.ts
+++ b/src/util/framerate.spec.ts
@@ -71,10 +71,10 @@ describe("FrameRateCounter", () => {
       100,
       15,
     );
-    
+
     // Without any frames, the downsampling rate is 4
     expect(frameRateCounter.calculateDownsamplingRate()).toEqual(4);
-    
+
     // 80ms / 100ms < 1, so no downsampling
     for (let i = 0; i < 10; i++) {
       frameRateCounter.addFrame(i * 80);
@@ -86,19 +86,19 @@ describe("FrameRateCounter", () => {
       frameRateCounter.addFrame(i * 400);
     }
     expect(frameRateCounter.calculateDownsamplingRate()).toEqual(4);
-  
+
     // Better fps now, but the high rate persists for a while
     for (let i = 0; i < 10; i++) {
       frameRateCounter.addFrame(i * 50);
     }
     expect(frameRateCounter.calculateDownsamplingRate()).toEqual(4);
-    
+
     // The downsampling rate will eventually drop
     for (let i = 0; i < 10; i++) {
       frameRateCounter.addFrame(i * 50);
     }
     expect(frameRateCounter.calculateDownsamplingRate()).toEqual(1);
-    
+
     // If the frame rate is very bad, still caps at 8
     frameRateCounter.resetForNewFrameSet();
     expect(frameRateCounter.calculateDownsamplingRate()).toEqual(1);

```

</details>

**Pull request merged**
